name: CSR Sync
# Runs on all pushes that pass checks and are merged into main.
on:
  push:
    branches:
      - "main"
jobs:
  Sync:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the repo at the current head
      - uses: actions/checkout@v3
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          fetch-depth: 0
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.AUTO_PRIVATE_KEY }}
          name: jake94a-gh-csr_test_id_ed25519
          # known_hosts placeholder must remain or this step will error out
          known_hosts: unnecessary
      - name: update csr
        env:
          AUTO_USERNAME: auto
          AUTO_USER_EMAIL: jakea@brightplanetsolar.com
          CSR_REPO: ssh://jakea@brightplanetsolar.com@source.developers.google.com:2022/p/bps-273522/r/test
          IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
          REMOTE: google
        run: |
          git config --global user.name $AUTO_USERNAME
          git config --global user.email $AUTO_USER_EMAIL
          git remote add $REMOTE $CSR_REPO
          git remote -v
          git pull $REMOTE main --rebase
        # git add .
        # git commit -m "updated by auto | app commit sha $IMAGE_TAG"
        # git push -u $REMOTE main
